# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('area', models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west'), ('CT', 'Central'), ('ME', 'Marine-east'), ('MW', 'Marine-west'), ('MC', 'Marine-central'), ('IW', 'Island-wide'), ('UN', 'Unknown')], default='UN', max_length=5)),
                ('level', models.IntegerField(default=0)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.DateTimeField(auto_now=True)),
                ('longitude', models.FloatField(blank=True, default=103.851959)),
                ('latitude', models.FloatField(blank=True, default=1.29027)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('type', models.CharField(choices=[('PKM', 'Among pokemons'), ('PKMHM', 'Among pokemons and humans'), ('UN', 'Unknown')], default='UN', max_length=5)),
                ('area', models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west'), ('CT', 'Central'), ('ME', 'Marine-east'), ('MW', 'Marine-west'), ('MC', 'Marine-central'), ('IW', 'Island-wide'), ('UN', 'Unknown')], default='UN', max_length=5)),
                ('level', models.IntegerField(default=0)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.DateTimeField(auto_now=True)),
                ('witness', models.CharField(blank=True, default='Public', max_length=20)),
                ('longitude', models.FloatField(blank=True, default=103.851959)),
                ('latitude', models.FloatField(blank=True, default=1.29027)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(blank=True, choices=[('UN', 'Unknown'), ('NM', 'Normal'), ('FR', 'Fire'), ('FT', 'Fighting'), ('WT', 'Water'), ('FY', 'Flying'), ('GS', 'Grass'), ('PS', 'Poison'), ('EC', 'Electronic'), ('GR', 'Ground'), ('PC', 'Psychic'), ('RK', 'Rock'), ('IC', 'Ice'), ('BG', 'Bug'), ('DG', 'Dragon'), ('GH', 'Ghost'), ('DK', 'Dark'), ('ST', 'Steel'), ('FY', 'Fairy')], max_length=5)),
                ('ability', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('area', models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west'), ('CT', 'Central'), ('ME', 'Marine-east'), ('MW', 'Marine-west'), ('MC', 'Marine-central'), ('IW', 'Island-wide'), ('UN', 'Unknown')], default='UN', max_length=5)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('longitude', models.FloatField(blank=True, default=103.851959)),
                ('latitude', models.FloatField(blank=True, default=1.29027)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=5)),
                ('type', models.CharField(blank=True, choices=[('SG', 'SINGAPOREAN'), ('FO', 'FOREIGNER')], max_length=10)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('SG', 'SINGAPOREAN'), ('FO', 'FOREIGNER')], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Trainer'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.PokemonDB'),
        ),
        migrations.AddField(
            model_name='crisis',
            name='incident',
            field=models.ManyToManyField(to='cms.Incident'),
        ),
        migrations.AddField(
            model_name='crisis',
            name='responseUnit',
            field=models.ManyToManyField(blank=True, to='cms.ResponseUnit'),
        ),
        migrations.AddField(
            model_name='crisis',
            name='trainer',
            field=models.ManyToManyField(blank=True, to='cms.Trainer'),
        ),
    ]
