# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west'), ('CT', 'Central'), ('ME', 'Marine-east'), ('MW', 'Marine-west'), ('MC', 'Marine-central'), ('IW', 'Island-wide'), ('UN', 'Unknown')], default='UN', max_length=20)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PKM', 'Among pokemons'), ('PKMHM', 'Among pokemons and humans'), ('UN', 'Unknown')], default='UN', max_length=20)),
                ('area', models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west'), ('CT', 'Central'), ('ME', 'Marine-east'), ('MW', 'Marine-west'), ('MC', 'Marine-central'), ('IW', 'Island-wide'), ('UN', 'Unknown')], default='UN', max_length=20)),
                ('level', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, default='', max_length=300)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(blank=True)),
                ('witness', models.CharField(default='Public', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west'), ('CT', 'Central'), ('ME', 'Marine-east'), ('MW', 'Marine-west'), ('MC', 'Marine-central'), ('IW', 'Island-wide'), ('UN', 'Unknown')], default='UN', max_length=20)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='crisis',
            name='incident',
            field=models.ManyToManyField(to='cms.Incident'),
        ),
        migrations.AddField(
            model_name='crisis',
            name='responseUnit',
            field=models.ManyToManyField(to='cms.ResponseUnit'),
        ),
    ]
