# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_cn', models.CharField(blank=True, max_length=30)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=5)),
                ('type', models.CharField(choices=[('FR', 'Fire'), ('FO', 'FOREIGNER')], max_length=5)),
                ('ability', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=5)),
                ('type', models.CharField(choices=[('SG', 'SINGAPOREAN'), ('FO', 'FOREIGNER')], max_length=10)),
                ('dob', models.DateTimeField(blank=True)),
                ('nationality', models.CharField(choices=[('SG', 'SINGAPOREAN'), ('FO', 'FOREIGNER')], max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='createdTime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='updatedTime',
            new_name='updated_time',
        ),
        migrations.AddField(
            model_name='crisis',
            name='comment',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='crisis',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='crisis',
            name='latitude',
            field=models.FloatField(default=1.29027),
        ),
        migrations.AddField(
            model_name='crisis',
            name='longitude',
            field=models.FloatField(default=103.851959),
        ),
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.FloatField(default=1.29027),
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.FloatField(default=103.851959),
        ),
        migrations.AddField(
            model_name='responseunit',
            name='address',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responseunit',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='responseunit',
            name='email',
            field=models.EmailField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responseunit',
            name='latitude',
            field=models.FloatField(default=1.29027),
        ),
        migrations.AddField(
            model_name='responseunit',
            name='longitude',
            field=models.FloatField(default=103.851959),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='area',
            field=models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west'), ('CT', 'Central'), ('ME', 'Marine-east'), ('MW', 'Marine-west'), ('MC', 'Marine-central'), ('IW', 'Island-wide'), ('UN', 'Unknown')], default='UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='incident',
            name='area',
            field=models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west'), ('CT', 'Central'), ('ME', 'Marine-east'), ('MW', 'Marine-west'), ('MC', 'Marine-central'), ('IW', 'Island-wide'), ('UN', 'Unknown')], default='UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('PKM', 'Among pokemons'), ('PKMHM', 'Among pokemons and humans'), ('UN', 'Unknown')], default='UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='area',
            field=models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west'), ('CT', 'Central'), ('ME', 'Marine-east'), ('MW', 'Marine-west'), ('MC', 'Marine-central'), ('IW', 'Island-wide'), ('UN', 'Unknown')], default='UN', max_length=5),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Trainer'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.PokemonDB'),
        ),
    ]
