# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(blank=True)),
                ('area', models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west'), ('CT', 'Central'), ('ME', 'Marine-east'), ('MW', 'Marine-west'), ('MC', 'Marine-central'), ('IW', 'Island-wide'), ('UN', 'Unknown')], default='UN', max_length=5)),
                ('status', models.BooleanField(default=False)),
                ('longitude', models.FloatField(blank=True, default=103.851959)),
                ('latitude', models.FloatField(blank=True, default=1.29027)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(blank=True)),
                ('temperature_low', models.IntegerField(blank=True)),
                ('temperature_hi', models.IntegerField(blank=True)),
                ('weather', models.CharField(blank=True, choices=[('UN', 'Unknown'), ('CD', 'Cloudy'), ('RN', 'Rainy'), ('SN', 'Sunny'), ('TS', 'Thunderstorm'), ('FG', 'Foggy')], default='UN', max_length=5)),
                ('psi', models.IntegerField(blank=True)),
            ],
        ),
    ]
