# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160919_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemondb',
            name='sex',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='', max_length=5),
            preserve_default=False,
        ),
    ]
