# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_shelter_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='shelter',
            field=models.ManyToManyField(blank=True, to='cms.Shelter'),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='incident',
            field=models.ManyToManyField(blank=True, to='cms.Incident'),
        ),
    ]
