# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20160919_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisis',
            name='latitude',
            field=models.FloatField(blank=True, default=1.29027),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='longitude',
            field=models.FloatField(blank=True, default=103.851959),
        ),
        migrations.AlterField(
            model_name='incident',
            name='comment',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='incident',
            name='latitude',
            field=models.FloatField(blank=True, default=1.29027),
        ),
        migrations.AlterField(
            model_name='incident',
            name='longitude',
            field=models.FloatField(blank=True, default=103.851959),
        ),
        migrations.AlterField(
            model_name='incident',
            name='updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='witness',
            field=models.CharField(blank=True, default='Public', max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemondb',
            name='type',
            field=models.CharField(blank=True, choices=[('UN', 'Unknown'), ('NM', 'Normal'), ('FR', 'Fire'), ('FT', 'Fighting'), ('WT', 'Water'), ('FY', 'Flying'), ('GS', 'Grass'), ('PS', 'Poison'), ('EC', 'Electronic'), ('GR', 'Ground'), ('PC', 'Psychic'), ('RK', 'Rock'), ('IC', 'Ice'), ('BG', 'Bug'), ('DG', 'Dragon'), ('GH', 'Ghost'), ('DK', 'Dark'), ('ST', 'Steel'), ('FY', 'Fairy')], max_length=5),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='latitude',
            field=models.FloatField(blank=True, default=1.29027),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='longitude',
            field=models.FloatField(blank=True, default=103.851959),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='nationality',
            field=models.CharField(blank=True, choices=[('SG', 'SINGAPOREAN'), ('FO', 'FOREIGNER')], max_length=5),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='type',
            field=models.CharField(blank=True, choices=[('SG', 'SINGAPOREAN'), ('FO', 'FOREIGNER')], max_length=10),
        ),
    ]
