# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_incident_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
        migrations.RenameField(
            model_name='crisis',
            old_name='created_by',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='crisis',
            old_name='incident',
            new_name='incidents',
        ),
        migrations.RenameField(
            model_name='crisis',
            old_name='responseUnit',
            new_name='responseUnits',
        ),
        migrations.RenameField(
            model_name='crisis',
            old_name='shelter',
            new_name='shelters',
        ),
        migrations.RenameField(
            model_name='crisis',
            old_name='trainer',
            new_name='trainers',
        ),
        migrations.RenameField(
            model_name='crisis',
            old_name='updated_by',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='created_by',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='updated_by',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='crisis',
            name='status',
            field=models.CharField(choices=[(b'INA', b'Inactive'), (b'ACT', b'Active'), (b'PEN', b'Pending'), (b'ARC', b'Archived')], default=b'UN', max_length=5),
        ),
        migrations.AddField(
            model_name='crisis',
            name='threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crisis',
            name='type',
            field=models.CharField(choices=[(b'LA', b'Land'), (b'SE', b'Sea'), (b'AI', b'Air')], default=b'UN', max_length=5),
        ),
        migrations.AddField(
            model_name='responseunit',
            name='speciality',
            field=models.CharField(choices=[(b'LA', b'Land'), (b'SE', b'Sea'), (b'AI', b'Air')], default=b'UN', max_length=5),
        ),
        migrations.AddField(
            model_name='responseunit',
            name='type',
            field=models.CharField(choices=[(b'LA', b'Land'), (b'SE', b'Sea'), (b'AI', b'Air')], default=b'UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[(b'LA', b'Land'), (b'SE', b'Sea'), (b'AI', b'Air')], default=b'UN', max_length=5),
        ),
    ]
