# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20160919_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='title',
            new_name='incident_title',
        ),
    ]
