# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20161018_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='handle_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.ResponseUnit'),
        ),
    ]
