# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_incident_handle_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisis',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='crisis',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='crisis',
            name='shelters',
        ),
        migrations.RemoveField(
            model_name='crisis',
            name='trainers',
        ),
        migrations.AlterField(
            model_name='crisis',
            name='area',
            field=models.CharField(choices=[(b'NE', b'North-east'), (b'SE', b'South-east'), (b'NW', b'North-west'), (b'NS', b'North-west')], default=b'UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='type',
            field=models.CharField(choices=[(b'LAN', b'Land'), (b'SEA', b'Sea'), (b'AIR', b'Air'), (b'TRA', b'Trainer')], default=b'UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='incident',
            name='area',
            field=models.CharField(choices=[(b'NE', b'North-east'), (b'SE', b'South-east'), (b'NW', b'North-west'), (b'NS', b'North-west')], default=b'UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[(b'LAN', b'Land'), (b'SEA', b'Sea'), (b'AIR', b'Air'), (b'TRA', b'Trainer')], default=b'UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='area',
            field=models.CharField(choices=[(b'NE', b'North-east'), (b'SE', b'South-east'), (b'NW', b'North-west'), (b'NS', b'North-west')], default=b'UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='speciality',
            field=models.CharField(choices=[(b'LAN', b'Land'), (b'SEA', b'Sea'), (b'AIR', b'Air'), (b'TRA', b'Trainer')], default=b'UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='type',
            field=models.CharField(choices=[(b'LAN', b'Land'), (b'SEA', b'Sea'), (b'AIR', b'Air'), (b'TRA', b'Trainer')], default=b'UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='area',
            field=models.CharField(choices=[(b'NE', b'North-east'), (b'SE', b'South-east'), (b'NW', b'North-west'), (b'NS', b'North-west')], default=b'UN', max_length=5),
        ),
    ]
