# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20160919_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='created_time',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='crisis',
            name='created_by',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crisis',
            name='updated_by',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_by',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
