# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20161018_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='status',
            new_name='resolved',
        ),
        migrations.RemoveField(
            model_name='crisis',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='crisis',
            name='type',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='level',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='witness',
        ),
        migrations.AlterField(
            model_name='crisis',
            name='status',
            field=models.CharField(choices=[(b'INA', b'Inactive'), (b'ACT', b'Active'), (b'PEN', b'Pending'), (b'ARC', b'Archived')], default=b'INA', max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[(b'LAN', b'Land'), (b'SEA', b'Sea'), (b'AIR', b'Air')], default=b'LAN', max_length=5),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='speciality',
            field=models.CharField(choices=[(b'LAN', b'Land'), (b'SEA', b'Sea'), (b'AIR', b'Air')], default=b'LAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='type',
            field=models.CharField(choices=[(b'MIL', b'Military'), (b'POL', b'Police'), (b'TRA', b'Trainer')], default=b'POL', max_length=10),
        ),
    ]
