# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20161019_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='handle_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.ResponseUnit'),
        ),
    ]
