# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20161019_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisis',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
