# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20161019_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisis',
            name='status',
            field=models.CharField(choices=[(b'ACT', b'Active'), (b'PEN', b'Pending'), (b'ARC', b'Archived')], default=b'ACT', max_length=10),
        ),
    ]
