# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20161024_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisis',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('PEN', 'Pending'), ('ARC', 'Archived')], default='ACT', max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='area',
            field=models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west')], default='UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('LAN', 'Land'), ('SEA', 'Sea'), ('AIR', 'Air')], default='LAN', max_length=5),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='area',
            field=models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west')], default='UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='speciality',
            field=models.CharField(choices=[('LAN', 'Land'), ('SEA', 'Sea'), ('AIR', 'Air')], default='LAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='type',
            field=models.CharField(choices=[('MIL', 'Military'), ('POL', 'Police'), ('TRA', 'Trainer')], default='POL', max_length=10),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='area',
            field=models.CharField(choices=[('NE', 'North-east'), ('SE', 'South-east'), ('NW', 'North-west'), ('NS', 'North-west')], default='UN', max_length=5),
        ),
    ]
