# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-06 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20161105_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='area',
            field=models.CharField(choices=[(b'NE', b'North-east'), (b'NW', b'North-west'), (b'SE', b'South-east'), (b'SW', b'South-west')], default=b'UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='responseunit',
            name='area',
            field=models.CharField(choices=[(b'NE', b'North-east'), (b'NW', b'North-west'), (b'SE', b'South-east'), (b'SW', b'South-west')], default=b'UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='area',
            field=models.CharField(choices=[(b'NE', b'North-east'), (b'NW', b'North-west'), (b'SE', b'South-east'), (b'SW', b'South-west')], default=b'UN', max_length=5),
        ),
    ]
